services:
  - type: web
    name: enlighten-ed
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: enlighten_ed_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 4

  - type: redis
    name: enlighten-ed-redis
    ipAllowList: []
    plan: free

databases:
  - name: enlighten_ed_db
    databaseName: enlighten_ed
    user: enlighten_ed_user
    plan: free
